spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/yyxn_database?useSLL=false&createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: admin
